### ISSUE TITLE
Missing VPC Infrastructure Services custom IAM roles doc

### ISSUE THREAD

**Issue by mekaufman** [ibm-cloud-docs/vpc#89] opened 2021-11-17 14:17 UTC
From @pkehnel 

The existing IAM Service: **VPC Infrastructure Services** is not documented in: https://cloud.ibm.com/docs/account?topic=account-iam-service-roles-actions#virtual-private-cloud

![Screenshot 2021-11-15 at 11 10 10](https://user-images.githubusercontent.com/23440847/141763227-b3a0dfcb-e703-4000-8a75-2cea2d5ae08b.png)

It contains uncommon service access attributes, like `Bare Metal Advances Network Operator`, for which we require API names.

**Comment by amatetic** [comment] 2022-02-07 17:44
Thank you for your feedback @mekaufman We will take a closer look at your comments in a upcoming sprints.

**Comment by austinmama** [comment] 2022-03-01 16:52
Adding @amatetic as assignee so my queries for networking team to-do's are up-to-date (we pull from Assignees). Please reassign as needed.

**Comment by amatetic** [comment] 2022-08-30 16:22
closing this item as a duplicate of Jira item CFD-4423

**Closed as completed by amatetic** 2022-08-30 16:22 UTC
