### ISSUE TITLE
Deleting a VPC using the REST APIs - curl commands

### ISSUE THREAD

**Issue by JCalabuig** [ibm-cloud-docs/vpc#15] opened 2019-09-26 18:28 UTC
The following curl commands return an error.  Removing the backslash and spaces before -H they all work:
curl -X GET "$api_endpoint/v1/subnets?version=$version&generation=2" \     
     -H "Authorization:$iam_token"
curl -X GET "$api_endpoint/v1/instances?version=$version&generation=2" \     
     -H "Authorization:$iam_token"
curl -X DELETE "$api_endpoint/v1/instances/$vsi?version=$version&generation=2" \     
     -H "Authorization:$iam_token"
curl -X GET "$api_endpoint/v1/instances/$vsi/network_interfaces?version=$version&generation=2" \     
     -H "Authorization:$iam_token"
curl -X DELETE "$api_endpoint/v1/subnets/$subnet?version=$version&generation=2" \     
     -H "Authorization:$iam_token"
curl -X GET "$api_endpoint/v1/public_gateways?version=$version&generation=2" \     
     -H "Authorization:$iam_token"
curl -X DELETE "$api_endpoint/v1/public_gateways/$gateway?version=$version&generation=2" \     
     -H "Authorization:$iam_token"
curl -X DELETE "$api_endpoint/v1/vpcs/$vpc?version=$version&generation=2" \     
     -H "Authorization:$iam_token"

**Comment by dhudlow** [comment] 2019-10-02 14:43
@JCalabuig Can you tell me a little more about your environment? Backslash-escaped line breaks are pretty widely supported as far as I know.

**Comment by JCalabuig** [comment] 2019-10-02 14:57
@dhudlow I am using Mac Terminal (MacOS Mojave v10.14.6)

**Comment by stemke** [comment] 2019-11-20 23:08
@JCalabuig - Are you still encountering the behavior you noted? It sounds like we were unable to reproduce the issue. Thank you for the follow-up.

**Comment by stemke** [comment] 2019-12-17 13:04
Given the age of this issue, and since we can't reproduce, I am closing it out. Please feel free to open any new issues in the future. We truly appreciate the input and feedback.  Thanks.

**Closed** 2019-12-17 13:47 UTC
